/* #region Quests */
/* ============================================================================================================================ */

DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralSamurai0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralSamurai0812', 0, 10, 'KillTaskSpectralSamurai0812', '2020-09-28 06:51:50');


DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralSamuraiCompleted0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralSamuraiCompleted0812', 72000, -1, 'KillTaskSpectralSamuraiCompleted0812', '2020-09-28 18:51:50');

/* ============================================================================================================================ */

DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralMinion0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralMinion0812', 0, 15, 'KillTaskSpectralMinion0812', '2020-09-28 06:51:50');


DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralMinionCompleted0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralMinionCompleted0812', 72000, -1, 'KillTaskSpectralMinionCompleted0812', '2020-09-28 18:51:50');

/* ============================================================================================================================ */

/* ============================================================================================================================ */

DELETE FROM `quest` WHERE `name` = 'KillTaskGolemSamurai0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskGolemSamurai0812', 0, 10, 'KillTaskGolemSamurai0812', '2020-09-28 06:51:50');


DELETE FROM `quest` WHERE `name` = 'KillTaskGolemSamuraiCompleted0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskGolemSamuraiCompleted0812', 72000, -1, 'KillTaskGolemSamuraiCompleted0812', '2020-09-28 18:51:50');

/* ============================================================================================================================ */

DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralBushi0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralBushi0812', 0, 10, 'KillTaskSpectralBushi0812', '2020-09-28 06:51:50');


DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralBushiCompleted0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralBushiCompleted0812', 72000, -1, 'KillTaskSpectralBushiCompleted0812', '2020-09-28 18:51:50');

/* ============================================================================================================================ */

DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralBloodMages0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralBloodMages0812', 0, 5, 'KillTaskSpectralBloodMages0812', '2020-09-28 06:51:50');


DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralBloodmagesCompleted0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralBloodmagesCompleted0812', 72000, -1, 'KillTaskSpectralBloodmagesCompleted0812', '2020-09-28 18:51:50');

/* ============================================================================================================================ */

DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralClawsBlades0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralClawsBlades0812', 0, 5, 'KillTaskSpectralClawsBlades0812', '2020-09-28 06:51:50');


DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralClawsBladesCompleted0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralClawsBladesCompleted0812', 72000, -1, 'KillTaskSpectralClawsBladesCompleted0812', '2020-09-28 18:51:50');

/* ============================================================================================================================ */

DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralNinjas0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralNinjas0812', 0, 10, 'KillTaskSpectralNinjas0812', '2020-09-28 06:51:50');


DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralNinjasCompleted0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralNinjasCompleted0812', 72000, -1, 'KillTaskSpectralNinjasCompleted0812', '2020-09-28 18:51:50');

/* ============================================================================================================================ */


DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralArchers0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralArchers0812', 0, 15, 'KillTaskSpectralArchers0812', '2020-09-28 06:51:50');


DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralArchersCompleted0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralArchersCompleted0812', 72000, -1, 'KillTaskSpectralArchersCompleted0812', '2020-09-28 18:51:50');

/* ============================================================================================================================ */

DELETE FROM `quest` WHERE `name` = 'KillSpectralNanjouShoujens0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillSpectralNanjouShoujens0812', 0, 5, 'KillSpectralNanjouShoujens0812', '2020-09-28 06:51:50');


DELETE FROM `quest` WHERE `name` = 'KillTaskSpectralNanjouShoujensCompleted0812';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('KillTaskSpectralNanjouShoujensCompleted0812', 72000, -1,'KillTaskSpectralNanjouShoujensCompleted0812', '2020-09-28 18:51:50');

/* ============================================================================================================================ */

DELETE FROM `quest` WHERE `name` = 'sarcophaguskillcount';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('sarcophaguskillcount', 0, 4, 'sarcophaguskillcount', '2020-09-28 06:51:50');


DELETE FROM `quest` WHERE `name` = 'SarcophagusKillTask';

INSERT INTO `quest` (`name`, `min_Delta`, `max_Solves`, `message`, `last_Modified`)
VALUES ('SarcophagusKillTask', 72000, -1,'SarcophagusKillTask', '2020-09-28 18:51:50');

/* #endregion Quests */
/* ============================================================================================================================ */
/* #region Recipes   */     

/* #region Recipe for Hoshimo Gate Key */

/* ===============================================================================*/
/* Combine the 46598 (lower) to 46599 (middle) to make 46601 (Broken lever)       */
/* ===============================================================================*/

DELETE FROM `recipe` WHERE `id` = 8900;

INSERT INTO `recipe` (`id`, `unknown_1`, `skill`, `difficulty`, `salvage_Type`, `success_W_C_I_D`, `success_Amount`, `success_Message`, `fail_W_C_I_D`, `fail_Amount`, `fail_Message`, `success_Destroy_Source_Chance`, `success_Destroy_Source_Amount`, `success_Destroy_Source_Message`, `success_Destroy_Target_Chance`, `success_Destroy_Target_Amount`, `success_Destroy_Target_Message`, `fail_Destroy_Source_Chance`, `fail_Destroy_Source_Amount`, `fail_Destroy_Source_Message`, `fail_Destroy_Target_Chance`, `fail_Destroy_Target_Amount`, `fail_Destroy_Target_Message`, `data_Id`, `last_Modified`)
VALUES (8900, 0, 0, 0, 0, 46601, 1, 'You have successfully combined the lower broken key of the Hoshimo Main Gate with the middle section.', 0, 0, '', 1, 1, '', 1, 1, '', 0, 0, '', 1, 1, '', 0, '2020-09-07 03:33:29');

DELETE FROM `cook_book` WHERE `recipe_Id` = 8900;

INSERT INTO `cook_book` (`recipe_Id`, `source_W_C_I_D`, `target_W_C_I_D`, `last_Modified`)
VALUES (8900, 46598, 46599, '2020-09-07 03:33:29');

/* ===============================================================================*/
/* Combine the 46601 (Broken Lever) to 46600 (Upper) to make 46459 (Main Gate Key)*/
/* ===============================================================================*/

DELETE FROM `recipe` WHERE `id` = 8901;

INSERT INTO `recipe` (`id`, `unknown_1`, `skill`, `difficulty`, `salvage_Type`, `success_W_C_I_D`, `success_Amount`, `success_Message`, `fail_W_C_I_D`, `fail_Amount`, `fail_Message`, `success_Destroy_Source_Chance`, `success_Destroy_Source_Amount`, `success_Destroy_Source_Message`, `success_Destroy_Target_Chance`, `success_Destroy_Target_Amount`, `success_Destroy_Target_Message`, `fail_Destroy_Source_Chance`, `fail_Destroy_Source_Amount`, `fail_Destroy_Source_Message`, `fail_Destroy_Target_Chance`, `fail_Destroy_Target_Amount`, `fail_Destroy_Target_Message`, `data_Id`, `last_Modified`)
VALUES (8901, 0, 0, 0, 0, 46459, 1, 'You have successfully combined the Broken Lever with the upper part of the Broken Key.', 0, 0, '', 1, 1, '', 1, 1, '', 0, 0, '', 1, 1, '', 0, '2020-09-07 03:33:29');

DELETE FROM `cook_book` WHERE `recipe_Id` = 7880;

INSERT INTO `cook_book` (`recipe_Id`, `source_W_C_I_D`, `target_W_C_I_D`, `last_Modified`)
VALUES (8901, 46601, 46600, '2020-09-07 03:33:29');

/* #endregion Recipe for Hoshimo Gate Key*/

/* ===============================================================================*/
/* 46427 Ancient Skull                                                            */
/* 46429 Ancient Arm Bone                                                         */
/* 46432 Shaped Arm Bone                                                          */
/* 46448 Ancient Skull and Bone                                                   */
/* 46447 Ancient Skull and Bones                                                  */
/* ===============================================================================*/

/* #region Recipe for Skull and Bone */

/* Combine the 46427 (Ancient Skull) to 46429 (Ancient Arm Bone) to make 46448 (Ancient Skull and Bone)       */

DELETE FROM `recipe` WHERE `id` = 108902;

INSERT INTO `recipe` (`id`, `unknown_1`, `skill`, `difficulty`, `salvage_Type`, `success_W_C_I_D`, `success_Amount`, `success_Message`, `fail_W_C_I_D`, `fail_Amount`, `fail_Message`, `success_Destroy_Source_Chance`, `success_Destroy_Source_Amount`, `success_Destroy_Source_Message`, `success_Destroy_Target_Chance`, `success_Destroy_Target_Amount`, `success_Destroy_Target_Message`, `fail_Destroy_Source_Chance`, `fail_Destroy_Source_Amount`, `fail_Destroy_Source_Message`, `fail_Destroy_Target_Chance`, `fail_Destroy_Target_Amount`, `fail_Destroy_Target_Message`, `data_Id`, `last_Modified`)
VALUES (108902, 0, 0, 0, 0, 46448, 1, 'You have successfully combined the Ancient Skull with the Ancient Arm Bone.', 0, 0, '', 1, 1, '', 1, 1, '', 0, 0, '', 1, 1, '', 0, '2020-09-07 03:33:29');

DELETE FROM `cook_book` WHERE `recipe_Id` = 108902;

INSERT INTO `cook_book` (`recipe_Id`, `source_W_C_I_D`, `target_W_C_I_D`, `last_Modified`)
VALUES (108902, 46427, 46429, '2020-09-07 03:33:29');

/* #endregion Recipe for Skull and Bone */

/* #region Recipe for Skull and Bones */

/* Combine the 46432 (Shaped Arm Bone) to 46448 (Ancient Skull and Bone) to make 46447 (Ancient Skull and Bones)       */

DELETE FROM `recipe` WHERE `id` = 108903;

INSERT INTO `recipe` (`id`, `unknown_1`, `skill`, `difficulty`, `salvage_Type`, `success_W_C_I_D`, `success_Amount`, `success_Message`, `fail_W_C_I_D`, `fail_Amount`, `fail_Message`, `success_Destroy_Source_Chance`, `success_Destroy_Source_Amount`, `success_Destroy_Source_Message`, `success_Destroy_Target_Chance`, `success_Destroy_Target_Amount`, `success_Destroy_Target_Message`, `fail_Destroy_Source_Chance`, `fail_Destroy_Source_Amount`, `fail_Destroy_Source_Message`, `fail_Destroy_Target_Chance`, `fail_Destroy_Target_Amount`, `fail_Destroy_Target_Message`, `data_Id`, `last_Modified`)
VALUES (108903, 0, 0, 0, 0, 46447, 1, 'You have successfully combined the Shaped Arm Bone with the Ancient Skull and Bone.', 0, 0, '', 1, 1, '', 1, 1, '', 0, 0, '', 1, 1, '', 0, '2020-09-07 03:33:29');

DELETE FROM `cook_book` WHERE `recipe_Id` = 108903;

INSERT INTO `cook_book` (`recipe_Id`, `source_W_C_I_D`, `target_W_C_I_D`, `last_Modified`)
VALUES (108903, 46448, 46432, '2020-09-07 03:33:29');

/* #endregion Recipe for Skull and Bones */

/* #endregion recipes */
